package com.core_network.model

import com.core_model.User

data class UserModel(
    val login: String?,
    val id: Long?,
    //val node_id: String?,
    val avatar_url: String?,
    //val gravatar_id: String?,
    val url: String?,
    //val html_url: String?,
    //val followers_url: String?,
    //val following_url: String?,
    //val gists_url: String?,
    //val starred_url: String?,
    //val subscriptions_url: String?,
    //val organizations_url: String?,
    //val repos_url: String?,
    //val events_url: String?,
    //val received_events_url: String?,
    val type: String?,
    //val site_admin: Boolean,
    //val name: String?,
    //val company: String?,
    //val blog: String?,
    //val location: String?,
    val email: String?,
    //val hireable: Boolean,
    val bio: String?,
    //val twitter_username: String?,
    val public_repos: Int?,
    val public_gists: Int?,
    val followers: Int?,
    val following: Int?,
    val created_at: String?,
    val updated_at: String?,
    val private_gists: Int?,
    val total_private_repos: Int?,
    val owned_private_repos: Int?,
    val disk_usage: Int?,
    val collaborators: Int?,
    val two_factor_authentication: Boolean
)

fun UserModel.toDomainModel(token: String): User = User(
    login = login.orEmpty(),
    id = id ?: -1,
    //node_id = node_id,
    avatar_url = avatar_url.orEmpty(),
    //gravatar_id = gravatar_id,
    url = url.orEmpty(),
    //html_url = html_url,
    //followers_url = followers_url,
    //following_url = following_url,
    //gists_url = gists_url,
    //starred_url = starred_url,
    //subscriptions_url = subscriptions_url,
    //organizations_url = organizations_url,
    //repos_url = repos_url,
    //events_url = events_url,
    //received_events_url = received_events_url,
    type = type.orEmpty(),
    //site_admin = site_admin,
    //name = name,
    //company = company,
    //blog = blog,
    //location = location,
    email = email.orEmpty(),
    //hireable = hireable,
    bio = bio.orEmpty(),
    //twitter_username = twitter_username,
    public_repos = public_repos ?: 0,
    public_gists = public_gists ?: 0,
    followers = followers ?: 0,
    following = following ?: 0,
    created_at = created_at.orEmpty(),
    updated_at = updated_at.orEmpty(),
    private_gists = private_gists ?: 0,
    total_private_repos = total_private_repos ?: 0,
    owned_private_repos = owned_private_repos ?: 0,
    disk_usage = disk_usage ?: 0,
    collaborators = collaborators ?: 0,
    two_factor_authentication = two_factor_authentication,
    token = token
)
